### Instructions:

- You can attempt any number of questions and in any order.  
  See the assignment page for a description of the hurdle requirement for this assessment.
- You may submit your practical for autograding as many times as you like to check on progress, however you will save time by checking and testing your own code before submitting.
- Develop and check your answers in the spaces provided.
- **Replace** the code `raise NotImplementedError()` with your solution to the question.
- Do **NOT** remove any variables other provided markings already provided in the answer spaces.
- Do **NOT** make any changes to this notebook outside of the spaces indicated.  
  (If you do this, the submission system might not accept your work)

### Submitting:

1. Before you turn this problem in, make sure everything runs as expected by resetting this notebook.    
   (You can do this from the menubar above by selecting `Kernel`&#8594;`Restart Kernel and Run All Cells...`)
1. Don't forget to save your notebook after this step.
1. Submit your .ipynb file to Gradescope via file upload or GitHub repository.
1. You can submit as many times as needed.
1. You **must** give your submitted file the **identical** filename to that which you downloaded without changing **any** aspects - spaces, underscores, capitalisation etc. If your operating system has changed the filename because you downloaded the file twice or more you **must** also fix this.  



---

# <mark style="background: #2dc26b; color: #ffffff;" >&nbsp;B3&nbsp;</mark>&ensp;Topic 8: Sorting (ii)

In [1]:
import numpy as np
from string import ascii_uppercase, ascii_lowercase
from random import shuffle

#### Question 01 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def lomuto_partition_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high range of indexes forming the partition to be conisdered for sorting and returns the quicksort pivot value using a Lomuto partition scheme or `None` for a zero length input array. The value of `high` is the actual list index considered.

For example:
```python
lomuto_partition_pivot([10, 9, 5, 2, 6, 4, 7, 1], 0, 7)
```
considers the whole list and returns the value `1` as the pivot value.

In [2]:
def lomuto_partition_pivot(arr, low, high):
    if high < low:
        return None  # Zero length input array
    pivot = arr[high]  # Selecting the last element as the pivot
    i = low - 1  # Index of the smaller element
    
    for j in range(low, high):
        if arr[j] < pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    
    # Place the pivot element in its correct position
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return arr[i + 1]  # Return the pivot value

arr = [10, 9, 5, 2, 6, 4, 7, 1]
pivot_value = lomuto_partition_pivot(arr, 0, 7)
print(pivot_value)     

1


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 02 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(5 Points)

Write a function defined as:
```python
def median_of_three_pivot(arr, low, high):
```
that accepts a list to be sorted and the low and high indexes of the partition to be conisdered for sorting and returns the quicksort pivot value using a median partition scheme or `None` for a zero length input array.

For example:
```python
median_of_three_pivot([10, 9, 5, 2, 6, 4, 7], 0, 6)
```
considers the whole list and returns the value `7` being the middle value in `10`, `2` and `7`.

In [5]:
def median_of_three_pivot(arr, low, high):
    if high < low:
        return None
    mid = (high+low)//2
    
    first = arr[low]
    middle = arr[mid]
    last = arr[high]
    
    if first<=middle<=last or last<=middle<=first:
        return middle
    elif middle<=first<=last or last<=first<=middle:
        return first
    else:
        return last
arr = [10, 9, 5, 2, 6, 4, 7]
pivot_value = median_of_three_pivot(arr, 0, 6)
print(pivot_value)  

7


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 03 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort(arr, reverse = False):
```
that uses a quicksort with median partition scheme to sort a list of floats in-place. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

In [7]:
def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def median_of_three(arr, low, high):
    mid = (low + high) // 2
    first = arr[low]
    middle = arr[mid]
    last = arr[high]
    if first <= middle <= last or last <= middle <= first:
        return mid
    elif middle <= first <= last or last <= first <= middle:
        return low
    else:
        return high

def quicksort(arr, low, high):
    if low < high:
        pivot_index = median_of_three(arr, low, high)
        arr[pivot_index], arr[high] = arr[high], arr[pivot_index]
        pivot_index = partition(arr, low, high)
        quicksort(arr, low, pivot_index - 1)
        quicksort(arr, pivot_index + 1, high)

def median_quicksort(arr, reverse=False):
    if reverse:
        arr.sort(reverse=True)
    else:
        quicksort(arr, 0, len(arr) - 1)

arr = [10.5, 3.2, 7.8, 1.4, 5.6]
median_quicksort(arr)
print(arr)  # Output: [1.4, 3.2, 5.6, 7.8, 10.5]

arr = [10.5, 3.2, 7.8, 1.4, 5.6]
median_quicksort(arr, reverse=True)
print(arr)  # Output: [10.5, 7.8, 5.6, 3.2, 1.4]

[1.4, 3.2, 5.6, 7.8, 10.5]
[10.5, 7.8, 5.6, 3.2, 1.4]


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 04 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
    def quicksort_numpy_arrays (alist, reverse = False):
```
that performs an ascending, inplace quicksort with a partition scheme of your choice on a list of NumPy arrays (`alist`) based on the sum of values in the array. The parameter `reverse` selects the direction of the sort order where `reverse == True` indicates a descending sort.

For example, give an input list of arrays like:
```python
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4])]
```
the function will sort alist in place like:
```python
[array([0]),
 array([0, 1, 2]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
```

In [8]:
def partition(arr, low, high):
    pivot = np.sum(arr[high])
    i = low - 1
    for j in range(low, high):
        if np.sum(arr[j]) <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quicksort(arr, low, high):
    if low < high:
        pivot_index = partition(arr, low, high)
        quicksort(arr, low, pivot_index - 1)
        quicksort(arr, pivot_index + 1, high)

def quicksort_numpy_arrays(alist, reverse=False):
    if reverse:
        alist.sort(key=lambda x: np.sum(x), reverse=True)
    else:
        quicksort(alist, 0, len(alist) - 1)

arrays = [
    np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
    np.array([0]),
    np.array([0, 1, 2]),
    np.array([0, 1, 2, 3, 4, 5, 6]),
    np.array([0, 1, 2, 3, 4])
]
quicksort_numpy_arrays(arrays)
print(arrays)
quicksort_numpy_arrays(arrays, reverse=True)
print(arrays)

[array([0]), array([0, 1, 2]), array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 5, 6, 7, 8])]
[array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([0, 1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4]), array([0, 1, 2]), array([0])]


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 05 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def quicksort_alphabetical (arr, ignorecase = False):
 ```
that sorts a list of characters (single letter strings) in-place according to alphabetical order. When `ignorecase == True`, the case of letters in the list should be ignored.  When `ignorecase == False`, the sort should respect the case of the list according to Python's default behaviour: uppercase characters sort in preference to lowercase characters. 

In [10]:
def partition(arr, low, high, ignorecase):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if (ignorecase and arr[j].lower() <= pivot.lower()) or (not ignorecase and arr[j] <= pivot):
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def quicksort(arr, low, high, ignorecase):
    if low < high:
        pivot_index = partition(arr, low, high, ignorecase)
        quicksort(arr, low, pivot_index - 1, ignorecase)
        quicksort(arr, pivot_index + 1, high, ignorecase)

def quicksort_alphabetical(arr, ignorecase=False):
    quicksort(arr, 0, len(arr) - 1, ignorecase)

# Example usage:
arr = ['b', 'A', 'd', 'C', 'a']
quicksort_alphabetical(arr)
print(arr)  # Output: ['A', 'C', 'a', 'b', 'd']

arr = ['b', 'A', 'd', 'C', 'a']
quicksort_alphabetical(arr, ignorecase=True)
print(arr)  # Output: ['a', 'A', 'b', 'C', 'd']


['A', 'C', 'a', 'b', 'd']
['A', 'a', 'b', 'C', 'd']


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 06 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```Python
def insertion_sort_string (un_list):
```
that sorts a list of strings in-place in descending order of their length using an insertion sort.

In [11]:
def insertion_sort_string (un_list):
    for i in range(1, len(un_list)):
        key = un_list[i]
        j = i - 1
        while j >= 0 and len(key) > len(un_list[j]):
            un_list[j + 1] = un_list[j]
            j -= 1
        un_list[j + 1] = key
strings = ['banana', 'apple', 'orange', 'grape', 'kiwi']
insertion_sort_string(strings)
print(strings)  # Output: ['banana', 'orange', 'apple', 'grape', 'kiwi']

['banana', 'orange', 'apple', 'grape', 'kiwi']


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 07 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_dict_by_key (un_dict):
```
that performs an insertion sort that sorts a dict by ascending values in-place while retaining identical keys.

For example, given a dictionary:
```python
d = {
    1: 101,
    2: 2,
    8: -1,
}
```
would be sorted as:
```python
d = {
    1: -1,
    2: 2,
    8: 101,
}
```

In [ ]:
def insertion_sort_dict_by_key (un_dict):
    

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 08 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def recursive_insertion_sort (arr, index, reverse):
```
that performs a recursive insertion sort in-place on a list of floats taking a `reverse` parameter to signal whether the floats are to be in ascending on descending order.

In [14]:
def recursive_insertion_sort (arr, index, reverse = False):
    if index < len(arr):
        key = arr[index]
        j = index - 1
        while j >= 0 and ((not reverse and arr[j] > key) or (reverse and arr[j] < key)):
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
        recursive_insertion_sort(arr, index + 1, reverse)

arr = [4.5, 2.1, 3.6, 1.8, 5.7]
recursive_insertion_sort(arr, 1, reverse=True)
print(arr)  # Output: [5.7, 4.5, 3.6, 2.1, 1.8]

[5.7, 4.5, 3.6, 2.1, 1.8]


In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 09 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_alpha_pivot(str_list, low, high):
```
that accepts a list of capitalised names, the index of the start and end of the partition in the list and returns a 'median of three' pivot value using a median partition scheme or `None` for a zero length input array. 

In calculating the pivot, the first letter of each string is given a weighting according to its index in `list(string.ascii_uppercase)` and the value returned is that index. 

Thus, in a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui"]
```
in calculating the pivot for the whole of the list, we consider the values:
- 12 (the index of 'M' in string.ascii_uppercase), 
- 23 (the index of 'X' in string.ascii_uppercase), and 
- 17 (the index of 'R' in string.ascii_uppercase)   
returning `17` as our first pivot value.


In [ ]:
def median_alpha_pivot(str_list, low, high):
    
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 10 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def median_quicksort_by_first_letter (str_list):
```   

that implements a **recursive** quicksort that sorts a list of capitalised names according to their first letter using the median partition scheme per the details expressed in Question 09. 

Thus, given a list like:
```python
["Majid", "Victoria", "Tashreque", "Xiefeng", "Fu", "Biao", "Rui", "Pranav"]
```
when sorted in-place, the list is:
```python
['Biao', 'Fu', 'Majid', 'Pranav', 'Rui', 'Tashreque', 'Victoria', 'Xiefeng']
```

In [ ]:
def median_quicksort_by_first_letter (str_list):

    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Testing Cell (Do NOT modify this cell)

#### Question 11 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

Write a function defined as:
```python
def insertion_sort_by_tuple_sum (ulist, reverse = False):
```
that sorts a list of numerical tuples in-place by the sum of all values in the tuple. The parameter `reverse` indicates an ascending or descending sort. 

In [15]:
def insertion_sort_by_tuple_sum (ulist, reverse = False):
    for i in range(1, len(ulist)):
        key = ulist[i]
        j = i - 1
        while j >= 0 and ((not reverse and sum(key) < sum(ulist[j])) or (reverse and sum(key) > sum(ulist[j]))):
            ulist[j + 1] = ulist[j]
            j -= 1
        ulist[j + 1] = key

ulist = [(1, 2), (4, 5), (3, 3), (2, 2)]
insertion_sort_by_tuple_sum(ulist)
print(ulist)  # Output: [(1, 2), (2, 2), (3, 3), (4, 5)]

ulist = [(1, 2), (4, 5), (3, 3), (2, 2)]
insertion_sort_by_tuple_sum(ulist, reverse=True)
print(ulist)  # Output: [(4, 5), (3, 3), (2, 2), (1, 2)]

[(1, 2), (2, 2), (3, 3), (4, 5)]
[(4, 5), (3, 3), (2, 2), (1, 2)]


In [ ]:
# Testing Cell (Do NOT modify this cell)

In [2]:
def custom_merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = custom_merge_sort(arr[:mid])
    right = custom_merge_sort(arr[mid:])

    return merge(left, right)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if isinstance(left[i], tuple) and isinstance(right[j], tuple):
            if sum(left[i]) > sum(right[j]):
                result.append(left[i])
                i += 1
            else:
                result.append(right[j])
                j += 1
        else:
            # Handling the case when the elements are not tuples (i.e., strings, numbers, etc.)
            if sum(map(lambda x: 0 if isinstance(x, str) else x, left[i])) > sum(map(lambda x: 0 if isinstance(x, str) else x, right[j])):
                result.append(left[i])
                i += 1
            else:
                result.append(right[j])
                j += 1

    while i < len(left):
        result.append(left[i])
        i += 1

    while j < len(right):
        result.append(right[j])
        j += 1

    return result

# Example usage:
data = [(2.4, 88, 2, "bee:"), (1, "s", None), (1, 1, 1, 1, 6), (1, 6.8)]

sorted_data = custom_merge_sort(data)
print(sorted_data)


TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [3]:
def custom_merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = custom_merge_sort(arr[:mid])
    right = custom_merge_sort(arr[mid:])

    return merge(left, right)

def tuple_sum(tup):
    return sum(x if isinstance(x, (int, float)) else 0 for x in tup)

def merge(left, right):
    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if isinstance(left[i], tuple) and isinstance(right[j], tuple):
            if tuple_sum(left[i]) > tuple_sum(right[j]):
                result.append(left[i])
                i += 1
            else:
                result.append(right[j])
                j += 1
        else:
            if isinstance(left[i], tuple):
                result.append(left[i])
                i += 1
            elif isinstance(right[j], tuple):
                result.append(right[j])
                j += 1

    while i < len(left):
        result.append(left[i])
        i += 1

    while j < len(right):
        result.append(right[j])
        j += 1

    return result

# Example usage:
data = [(2.4, 88, 2, "bee:"), (1, "s", None), (1, 1, 1, 1, 6), (1, 6.8)]

sorted_data = custom_merge_sort(data)
print(sorted_data)


[(2.4, 88, 2, 'bee:'), (1, 1, 1, 1, 6), (1, 6.8), (1, 's', None)]
